#config-service
---
server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Stan05/vehicle-dealership
          searchPaths: config-data
          username: Stan05
          password: s95052555